In [1]:
import numpy as np

In [3]:
#With "arange", we can create arrays just list we created lists with 'range'
#This gives us an array ranging from the numbers in the arguements

np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
#Want a blank array? Create it full of zeros with 'zeros'
#The argument within it creates the shape of a 2d or 3d array

np.zeros((3,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
#Hate zeros? Why not use 'ones'?!

np.ones((3,11))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
#Creating dummy data or need a random number?
#randint and randn are useful here

#Creates random numbers around a standard distribution from 0
#The arguement gives us the array's shape
print(np.random.randn(3,3))

#Creates random numbers between two numbers that we give it
#The third arguement gives us the shape of the array
print(np.random.randint(1,100, (3,3)))

[[ 1.62997597 -0.91454173 -0.91492484]
 [-0.69647442 -0.18315125  0.38253632]
 [ 0.5957525  -0.93627279 -0.5834644 ]]
[[93 11 91]
 [ 9 20 86]
 [ 6 96 73]]


In [2]:
#Three lists, one for player heights, one for player weights, one for names

PlayerNames = ["Alonso", "Rudiger", "Tomori", "James"]
PlayerHeights = [184, 188, 191, 193]
PlayerWeights = [81, 85, 103, 99]

#Create an array of names

print(np.array(PlayerNames))

#Create a matrix of all three lists, start with a list of lists

PlayerMatrix = [PlayerNames, PlayerHeights, PlayerWeights]
print(np.array(PlayerMatrix))

['Alonso' 'Rudiger' 'Tomori' 'James']
[['Alonso' 'Rudiger' 'Tomori' 'James']
 ['184' '188' '191' '193']
 ['81' '85' '103' '99']]


In [11]:
#Three lists, one for player heights, one for player weights, one for names
#Create an array with each list

PlayerNames = ["Alonso", "Rudiger", "Tomori", "James"]
PayerHeights = [184, 188, 191, 193]
PlayersWeights = [81, 85, 103, 99]

np.array(PlayerNames)
PlayerHeights = np.array(PlayerHeights)
np.array(PlayerWeights)

#What is the largest height, .max()?

PlayerHeights.max()

193

In [9]:
#What location is the max, .argmax()?

PlayerHeights.argmax()

3

In [12]:
#Can I use this method to locate the player's name?
#Instead of a number in the square bracks, I can just put this method

PlayerNames[PlayerHeights.argmax()]

'James'

In [13]:
import numpy as np

#Every 4 years since 1930
WCYears = np.arange(1930,2020,4)

#No World Cup in 1942 or 1946
WCYears = np.delete(WCYears, (3,4))

WCYears

array([1930, 1934, 1938, 1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978,
       1982, 1986, 1990, 1994, 1998, 2002, 2006, 2010, 2014, 2018])

In [14]:
#What year was the third world cup held?
WCYears[2]

1938

In [15]:
#Show me the 4 World Cup years following WW2
WCYears [3:7]

array([1950, 1954, 1958, 1962])

In [16]:
#Create our 2d array
WCYears = [2002,2006,2010,2014,2018]
WCHosts = ["Japan/Korea","Germany","South Africa","Brazil","Russia"]
WCWinners = ["Brazil","Italy","Spain","Germany","France"]

WCArray = np.array((WCYears,WCHosts,WCWinners))
WCArray

array([['2002', '2006', '2010', '2014', '2018'],
       ['Japan/Korea', 'Germany', 'South Africa', 'Brazil', 'Russia'],
       ['Brazil', 'Italy', 'Spain', 'Germany', 'France']], dtype='<U12')

In [17]:
#2010 is the third year, find the host in the second row
WCArray[1,2]

'South Africa'

In [18]:
#Find the winner of the last World Cup
#Negative Selection!

WCArray[2,-1]

'France'

In [19]:
WCYears = np.array([2002,2006,2010,2014,2018])
WCTopScorers = np.array(["Ronaldo","Klose","Muller","James Rodriguez","Kane"])
WCGoals = np.array([8,5,5,6,6])

In [20]:
#Where does the top scorer score more than 5 goals?
WCGoals > 5

array([ True, False, False,  True,  True])

In [21]:
#Not particularly useful, but we can use bracket selection with this!

WCTopScorers[(WCGoals>5)]

array(['Ronaldo', 'James Rodriguez', 'Kane'], dtype='<U15')

In [22]:
WCYears = [2002,2006,2010,2014,2018]
WCTopScorers = ["Ronaldo","Klose","Muller","James Rodriguez","Kane"]
WCGoals = [8,5,5,6,6]

WCTopArray = np.array((WCYears,WCTopScorers,WCGoals))
WCTopArray

array([['2002', '2006', '2010', '2014', '2018'],
       ['Ronaldo', 'Klose', 'Muller', 'James Rodriguez', 'Kane'],
       ['8', '5', '5', '6', '6']], dtype='<U15')

In [23]:
WCTopArray [1,2]

'Muller'

In [24]:
PlayerOne = {"Name":"Lucasinho",
"Number":8,
"Long Sleeves":True}

PlayerOne

{'Name': 'Lucasinho', 'Number': 8, 'Long Sleeves': True}

In [25]:
PlayerOne["Number"]

8

In [26]:
PlayerOne["Long Sleeves"] = False
PlayerOne["Size"] = "Medium"

PlayerOne

{'Name': 'Lucasinho', 'Number': 8, 'Long Sleeves': False, 'Size': 'Medium'}

In [27]:
del PlayerOne["Size"]

PlayerOne

{'Name': 'Lucasinho', 'Number': 8, 'Long Sleeves': False}

In [28]:
PlayerOne.clear()

PlayerOne

{}

In [29]:
GF = [0,0,3,2,1,5,3,1,2]
GA = [2,0,2,2,3,2,3,2,4]

print(GF)
print(GA)

[0, 0, 3, 2, 1, 5, 3, 1, 2]
[2, 0, 2, 2, 3, 2, 3, 2, 4]


In [30]:
print(GF[0])
print(GA[0])

0
2


In [31]:
GF[0] - GA[0]

-2

In [32]:
#Define variables for points and goal difference
#Set goals for and against

P = 0
GD = 0
GF = [0,0,3,2,1,5,3,1,2]
GA = [2,0,2,2,3,2,3,2,4]

#We have 9 games, so we iterate with a range of 9 in a for loop 
for i in range(9):
    #If we score more, give us 3 points and add the goal difference
    if GF[i] > GA[i]:
        P += 3
        GD += (GF[i] - GA[i])
    #If we draw, give us a point. Goal difference will stay the same.
    elif GF[i] == GA[i]:
        P += 1
    #If we lose, we get no points, but update the goal difference
    else:
        GD += (GF[i] - GA[i])
        
print(P)
print(GD)

9
-3


In [33]:
#One argument in range()
#Give me the list of 10 numbers, starting at 0
list (range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
#Two arguements in range()
#Give me all numbers between these two
list(range(5,10))

[5, 6, 7, 8, 9]

In [35]:
#Three arguements in range()
#Give me all numbers between the first two, in steps of the third number
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [36]:
Players = ["Terry","Cole","Cech","Lampard","Drogba"]

#Select the 4th player - remember that the count starts at 0!
print(Players[3])

#Select the middle 3 players
print(Players[1:4])

Lampard
['Cole', 'Cech', 'Lampard']


In [37]:
GF = [0,0,3,2,1,5,3,1,2]
GA = [2,0,2,2,3,2,3,2,4]

#Let's add a new score to our goals for and goals against lists
#The append() method will help us here

GF.append(3)
GA.append(1)

#Show the scores, 3-1 should be the final column
print(GF)
print(GA)

[0, 0, 3, 2, 1, 5, 3, 1, 2, 3]
[2, 0, 2, 2, 3, 2, 3, 2, 4, 1]


In [38]:
GF = [0, 0, 3, 2, 1, 5, 3, 1, 2, 3]
GA =[2, 0, 2, 2, 3, 2, 3, 2, 4, 1]

#I want to reverse the scores, to see the 5 most recent ones
#Reverse() will make this light work

GF.reverse()
GA.reverse()
print(GF[0:5])
print(GA[0:5])

[3, 2, 1, 3, 5]
[1, 4, 2, 3, 2]
